#
# Yamu Solutions device driver
#

obj-$(CONFIG_KeyBackLightDIMM) += KeyBackLightDIMM.o
obj-$(CONFIG_MATRIX) += matrix.o
#obj-$(CONFIG_HOLD) += hold.o
obj-$(CONFIG_BATTERY) += battery.o
obj-$(CONFIG_HDET) += hdet.o
#obj-$(CONFIG_LCDP) += lcdp.o
#obj-$(CONFIG_DACP) += dacp.o
#obj-$(CONFIG_AMPP) += ampp.o
#obj-$(CONFIG_MuteTR) += MuteTR.o
obj-$(CONFIG_WLANP) += wlanp.o
obj-$(CONFIG_MOTION) += motion.o
obj-$(CONFIG_LCDDIMM) += LCDDIMM.o
obj-$(CONFIG_IRTX) += irtx.o
#obj-$(CONFIG_IRRX) += irrx.o
obj-$(CONFIG_WHEEL) += wheel.o 
obj-$(CONFIG_PMODE) += pmode.o
obj-$(CONFIG_LcdReset) += LcdReset.o
#obj-$(CONFIG_LCDBacklightEn) +=LCDBacklightEn.o
#obj-$(CONFIG_MuteFET) +=MuteFET.o
obj-$(CONFIG_NANDWP) +=NANDWP.o
#obj-$(CONFIG_AG_OUT) += AG_OUT.o
#obj-$(CONFIG_BT_PRIORITY) += WLAN_BT_PRIORITY.o
obj-$(CONFIG_CHG_ACPR) +=CHG_ACPR.o
obj-$(CONFIG_CHG_HPWR) +=CHG_HPWR.o
obj-$(CONFIG_CHG_PPR) +=CHG_PPR.o
obj-$(CONFIG_CHG_SUSP) +=CHG_SUSP.o
obj-$(CONFIG_DOCKDET) +=DOCKDET.o
obj-$(CONFIG_WLAN_nRESET) +=WLAN_nRESET.o
obj-$(CONFIG_WLAN_SPI_nINT) +=WLAN_SPI_nINT.o
obj-$(CONFIG_WM8750_REG) +=WM8750Reg.o

obj-$(CONFIG_DOCKDET_AD) +=DOCKDET_AD.o
obj-$(CONFIG_WLAN_DC_EN) +=WLAN_DC_EN.o
obj-$(CONFIG_WLAN_SLEEP_CLK) +=WLAN_SLEEP_CLK.o
obj-$(CONFIG_SW_PW_OFF) +=PIC_SW_PW_OFF.o
obj-$(CONFIG_ACCEL) +=accel.o
