/*
 * include/asm-arm/arch-s3c2440/smdk.h
 * 
 * Copyright (C) 2004 Samsung Electronics Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef _SMDK2440_H_
#define _SMDK2440_H_

#ifndef __ASM_ARCH_HARDWARE_H
#error "include <asm/hardware.h> instead"
#endif

/* definition of IRQ */
#define IRQ_CS8900		IRQ_EINT9
#define IRQ_KBD			IRQ_EINT1
#define IRQ_nCF_INS		IRQ_EINT3
#define IRQ_CF_RDY		IRQ_EINT8
#define IRQ_SMDK_BT0		IRQ_EINT0
#define IRQ_SMDK_BT1		IRQ_EINT2
#define IRQ_SMDK_BT2		IRQ_EINT11
#define IRQ_SMDK_BT3		IRQ_EINT19

#define IRQ_nCD_SD		IRQ_EINT16
#define IRQ_SMDK_UP		IRQ_GPB5
#define IRQ_SMDK_DOWN		IRQ_GPB6
#define IRQ_SMDK_LEFT		IRQ_GPE11
#define IRQ_SMDK_RIGHT		IRQ_GPE12

/* CS8900a, nGCS3 */
#define pCS8900_BASE		0x19000000
#define vCS8900_BASE		0xd0000000

/* PCMCIA, nGCS2 */
#define pCF_MEM_BASE		0x10000000
#define vCF_MEM_BASE		0xd1000000
#define pCF_IO_BASE		0x11000000
#define vCF_IO_BASE		0xd2000000

#define GPIO_LED1		(GPIO_MODE_OUT | GPIO_PULLUP_DIS | GPIO_F4)
#define GPIO_LED2		(GPIO_MODE_OUT | GPIO_PULLUP_DIS | GPIO_F5)
#define GPIO_LED3		(GPIO_MODE_OUT | GPIO_PULLUP_DIS | GPIO_F6)
#define GPIO_LED4		(GPIO_MODE_OUT | GPIO_PULLUP_DIS | GPIO_F7)

#define GPIO_KBD_SPIMISO	(GPIO_MODE_ALT1 | GPIO_PULLUP_DIS | GPIO_G5)
#define GPIO_KBD_SPIMOSI	(GPIO_MODE_ALT1 | GPIO_PULLUP_DIS | GPIO_G6)
#define GPIO_KBD_SPICLK		(GPIO_MODE_ALT1 | GPIO_PULLUP_DIS | GPIO_G7)
#define GPIO_KBD_nSS		(GPIO_MODE_OUT | GPIO_PULLUP_DIS | GPIO_B6)
#define GPIO_KBD_WUK		(GPIO_MODE_OUT | GPIO_PULLUP_EN | GPIO_B0)

#define GPIO_SMDK_BT0		GPIO_F0
#define GPIO_SMDK_BT1		GPIO_F2
#define GPIO_SMDK_BT2		GPIO_G3
#define GPIO_SMDK_BT3		GPIO_G11

#define GPIO_nCF_INS		(GPIO_MODE_IN | GPIO_PULLUP_EN | GPIO_F3)
#define GPIO_CF_RDY		(GPIO_MODE_IN | GPIO_PULLUP_EN | GPIO_G8)
#define GPIO_nCD_SD		(GPIO_MODE_IN | GPIO_PULLUP_DIS | GPIO_G8)

#ifdef CONFIG_ARCH_S3C2440A
#define GPIO_IR_TXD		(GPIO_MODE_ALT0 | GPIO_PULLUP_DIS | GPIO_H6)
#define GPIO_IR_RXD		(GPIO_MODE_ALT0 | GPIO_PULLUP_DIS | GPIO_H7)
#define GPIO_UEXT_CLK		(GPIO_MODE_ALT0 | GPIO_PULLUP_DIS | GPIO_H8)
#endif

/* 
 * 031027 for meritech camera support
 * Meritech Board used */
#define GPIO_CAMDATA0		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J0)
#define GPIO_CAMDATA1		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J1)
#define GPIO_CAMDATA2		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J2)
#define GPIO_CAMDATA3		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J3)
#define GPIO_CAMDATA4		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J4)
#define GPIO_CAMDATA5		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J5)
#define GPIO_CAMDATA6		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J6)
#define GPIO_CAMDATA7		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J7)
#define GPIO_CAMPCLKIN		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J8)
#define GPIO_CAMVSYNC		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J9)
#define GPIO_CAMHREF		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J10)
#define GPIO_CAMPCLKOUT		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J11)
#define GPIO_CAMRESET		(GPIO_MODE_ALT0 | GPIO_PULLUP_EN | GPIO_J12)


#endif	/* _SMDK2440_H_ */
