#
# Makefile for the mc9sdz60 pmic drivers.
#

obj-y += mcu_pmic_gpio.o
obj-$(CONFIG_MXC_MC9SDZ60_ADC) += pmic_adc-mod.o
obj-$(CONFIG_MXC_MC9SDZ60_RTC) += pmic_rtc-mod.o
pmic_adc-mod-objs := mcu_pmic_adc.o
pmic_rtc-mod-objs := mcu_pmic_rtc.o

