#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-9tdmi-linux-gnu-gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_KRB5 -DOPENSSL_NO_RC5 -DOPENSSL_NO_IDEA -DTERMIO -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-elf-arm"
  #define DATE "Mon Aug 20 11:21:40 BST 2007"
#endif
