snd-soc-ac97-objs := ac97.o
snd-soc-wm8731-objs := wm8731.o
snd-soc-wm8750-objs := wm8750.o
snd-soc-wm8750-spi-objs := wm8750-spi.o
snd-soc-wm8750-i2c-objs := wm8750-i2c.o
snd-soc-wm8753-objs := wm8753.o
snd-soc-wm9712-objs := wm9712.o

obj-$(CONFIG_SND_SOC_AC97_CODEC)	+= snd-soc-ac97.o
obj-$(CONFIG_SND_SOC_WM8731)	+= snd-soc-wm8731.o
obj-$(CONFIG_SND_SOC_WM8750)	+= snd-soc-wm8750.o
obj-$(CONFIG_SND_SOC_WM8750_I2C) += snd-soc-wm8750-i2c.o
obj-$(CONFIG_SND_SOC_WM8750_SPI) += snd-soc-wm8750-spi.o
obj-$(CONFIG_SND_SOC_WM8753)	+= snd-soc-wm8753.o
obj-$(CONFIG_SND_SOC_WM9712)	+= snd-soc-wm9712.o
