#!/bin/sh

/bin/mount -a

echo "Mounting RAM Disk"
/bin/mount -t ramfs ramfs /tmp
/bin/mount -t ramfs ramfs /var
mkdir /var/shm /var/log /var/run

echo "Adding devices"
/bin/mknod /dev/watchdog c 10 130
ln -s /dev/sound/dsp /dev/dsp
ln -s /dev/misc/rtc /dev/rtc
ln -s /dev/fb/0 /dev/fb0

echo "String syslogd"
/sbin/syslogd

if [ -d /dev/mmc/blk0 ]; then
	echo "Mounting MMC/SD card"
	mount -t vfat /dev/mmc/blk0/part1 /mnt/mmc
fi

if ! [ -f /etc/firstboot ]; then
	echo "First boot"
	touch /etc/firstboot

	if [ -x /mnt/mmc/firstboot.sh ]; then
		(cd /mnt/mmc; ./firstboot.sh)
	fi
fi

if ! [ -f /etc/dropbear/dropbear_rsa_host_key ] ; then
    echo "Creating dropbear rsa host key"
    /usr/local/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
fi

if ! [ -f /etc/dropbear/dropbear_dss_host_key ]; then
    echo "Creating dropbear dss host key"
    /usr/local/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
fi

echo "Starting lo"
/sbin/ifconfig lo up 127.0.0.1

echo "Starting inetd"
/usr/sbin/inetd

# Start wlan
/etc/init.d/wlan-start

# echo "Starting accelerometer"
/sbin/insmod lis302dl.ko


if [ -x /etc/init.d/rcS.local ]; then
	echo "Running rcS.local"
	/etc/init.d/rcS.local
fi

if [ -x /mnt/mmc/jiveboot.sh ]; then
    (cd /mnt/mmc; ./jiveboot.sh)
fi

echo "Starting jive applications"
(cd /usr/bin; /usr/bin/jive &)
