#!/bin/sh

/bin/mount -a

echo "Mounting RAM Disk"
/bin/mount -t ramfs ramfs /tmp
/bin/mount -t ramfs ramfs /var
mkdir /var/shm /var/log /var/run


if [ -b /dev/mmcblk0p1 ]; then
	echo "Mounting MMC/SD card (partition 1)"
	mount -t vfat /dev/mmcblk0p1 /mnt/mmc
elif [ -b /dev/mmcblk0 ]; then
	echo "Mounting MMC/SD card (whole device)"
	mount -t vfat /dev/mmcblk0 /mnt/mmc
fi


grep /mnt/mmc /proc/mounts | cut -d' ' -f 4 | grep -q rw
if [ $? = 0 -a -e /mnt/mmc/var  ]; then
	# log and core files to mmc
	/bin/mkdir -p /mnt/mmc/var/log /mnt/mmc/var/core

	echo "Starting syslogd (to mmc)"
	/sbin/syslogd -O /mnt/mmc/var/log/messages

	echo "Enabling core files (to mmc)"
	echo "/mnt/mmc/var/core/core-%e" > /proc/sys/kernel/core_pattern
	ulimit -c unlimited
else
	# log to /var
	echo "Starting syslogd"
	/sbin/syslogd
fi


if ! [ -f /etc/firstboot ]; then
	echo "First boot"
	touch /etc/firstboot

	if [ -x /mnt/mmc/firstboot.sh ]; then
		(cd /mnt/mmc; ./firstboot.sh)
	fi
fi

if ! [ -f /etc/dropbear/dropbear_rsa_host_key ] ; then
	echo "Creating dropbear rsa host key"
	/usr/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
fi

if ! [ -f /etc/dropbear/dropbear_dss_host_key ]; then
	echo "Creating dropbear dss host key"
	/usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
fi

echo "Starting lo"
/sbin/ifconfig lo up 127.0.0.1

echo "Starting inetd"
/usr/sbin/inetd


# Start wlan
/etc/init.d/wlan-start


if [ -x /etc/init.d/rcS.local ]; then
	echo "Running rcS.local"
	/etc/init.d/rcS.local
fi

if [ -x /mnt/mmc/jiveboot.sh ]; then
    (cd /mnt/mmc; ./jiveboot.sh)
fi

echo "Starting jive applications"
(cd /usr/bin; /usr/bin/jive &)
