#!/bin/sh


# (Optional) number of seconds before wakeup
SECONDS=$1

if [ "x$SECONDS" != "x" ]
then
    NOW=`cat /sys/devices/platform/s3c2410-rtc/rtc\:rtc0/since_epoch`
    WAKEAT=$(($NOW + $SECONDS))

    echo "Wakeat $WAKEAT"
    echo $WAKEAT > /sys/devices/platform/s3c2410-rtc/rtc\:rtc0/wakealarm
fi


# Stop wlan
/etc/init.d/wlan stop

# Suspend
echo 'mem' > /sys/power/state

# Start wlan
/etc/init.d/wlan start

