#!/bin/sh


# Read network config
if [ -r /etc/network/config ]
then
    . /etc/network/config
fi


case "$1" in
    start)
	echo "Starting wlan"

	# Load wlan drivers
	/sbin/insmod gspi.ko
	/sbin/insmod gspi8xxx.ko helper_name=/lib/firmware/helper_gspi.bin fw_name=/lib/firmware/gspi8686.bin


	# Set MAC address using ethaddr parameter on kernel command line
	ethaddr=`/usr/sbin/fw_printenv ethaddr | cut -d= -f2`
	if [ "x${ethaddr}" != "x" ]
	    then
	    echo "Setting ethaddr: ${ethaddr}"
	    /sbin/ifconfig eth0 hw ether ${ethaddr}
	fi


	# Set region code
	if [ "x${REGIONCODE}" != "x" ]
	    then
	    echo "Setting region: ${REGIONCODE}"
	    /usr/sbin/iwpriv eth0 setregioncode ${REGIONCODE}
	fi

	# Enable power save
	/usr/sbin/iwconfig eth0 power on

	# Start wpa supplicant
	/usr/sbin/wpa_supplicant -B -Dmarvell -ieth0 -c/etc/wpa_supplicant.conf
	/usr/sbin/wpa_cli -B -a/etc/network/wpa_action
	;;

    stop)
	echo "Stopping wlan"

	# Stop wpa supplicant
	killall wpa_cli
	killall wpa_supplicant

	# Down the interface
	ifconfig eth0 down
	/bin/rm -rf /var/run/ifstate

	# Make sure udhcpc is killed
	kill -TERM `cat /var/run/udhcpc.eth0.pid`

	# Remove wlan drivers
	rmmod gspi8xxx gspi
	;;

    *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
