#
# Makefile for the mouse drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_BITSY)		+= h3600_ts_input.o
obj-$(CONFIG_TOUCHSCREEN_GUNZE)		+= gunze.o
obj-$(CONFIG_TOUCHSCREEN_S3C2440)	+= s3c2440_ts.o
obj-$(CONFIG_TOUCHSCREEN_S3C2413)	+= s3c2413_ts.o
