#
# @(#) sl@belcarra.com/whiskey.enposte.net|otg/platform/freescale/Makefile-l26|20070525074749|26894
# Copyright (c) 2006-2007 Belcarra Technologies 2005 Corp


ifdef CONFIG_OTG_ZASEVB
include drivers/otg/hardware/Makefile-zasevb-l26
endif
ifdef CONFIG_OTG_ZASEVB_ARC
include drivers/otg/hardware/Makefile-zasevb-arc-l26
endif
ifdef CONFIG_OTG_IMX31ADS
include drivers/otg/hardware/Makefile-imx31ads-l26
endif
