#!/bin/sh

# udhcpc script edited by Tim Riker <Tim@Rikers.org>

[ -z "$1" ] && echo "Error: should be called from udhcpc" && exit 1

RESOLV_CONF="/etc/resolv.conf"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
[ -n "$subnet" ] && NETMASK="netmask $subnet"

case "$1" in
	deconfig)
		/sbin/ifconfig $interface 0.0.0.0
		;;

	renew|bound|zeroconf)
		/sbin/ifconfig $interface $ip $BROADCAST $NETMASK

		while route del default gw 0.0.0.0 dev $interface ; do
			:
		done

		if [ -n "$router" ] ; then
			metric=0
			for i in $router ; do
				route add default gw $i dev $interface metric $metric
				metric=$metric+1
			done
		else
			route add default dev $interface
		fi

		echo -n > $RESOLV_CONF
		[ -n "$domain" ] && echo search $domain >> $RESOLV_CONF
		for i in $dns ; do
			echo adding dns $i
			echo nameserver $i >> $RESOLV_CONF
		done
		;;
esac

exit 0
