#!/bin/sh

IFNAME=$1
CMD=$2

/usr/bin/logger "wpa_action $IFNAME $CMD"

if [ "$CMD" = "CONNECTED" ]; then
    	# FIXME disabled, causes wifi to crash
	# Enable power save
	#/usr/sbin/iwconfig $IFNAME power on

	/sbin/ifup $IFNAME
fi

if [ "$CMD" = "DISCONNECTED" ]; then 
	# FIXME using ifdown kills the wifi
	/sbin/ifconfig $IFNAME 0.0.0.0
	/bin/rm -rf /var/run/ifstate

	# Make sure udhcpc is killed
	kill -TERM `cat /var/run/udhcpc.$IFNAME.pid`
fi

