#
# Makefile for Power Managment devices.
#

# Module dependencies for the MXC driver
obj-$(CONFIG_MXC_DPTC)		+= dptc.o

obj-$(CONFIG_MXC_DPTC)		+= dvfs_dptc.o

obj-$(CONFIG_MXC_DVFS)		+= dvfs_dptc.o

obj-$(CONFIG_MX27_DPTC)		+= dptc_mx27.o
