/*
 * Copyright 2005-2007 Freescale Semiconductor, Inc. All Rights Reserved.
 */

/*
 * The code contained herein is licensed under the GNU General Public
 * License. You may obtain a copy of the GNU General Public License
 * Version 2 or later at the following locations:
 *
 * http://www.opensource.org/licenses/gpl-license.html
 * http://www.gnu.org/copyleft/gpl.html
 */

/* Generated by otg-tests-c.awk
 *
 * Do not Edit, see otg-state.awk
 */

/* %Z %K */


/*!
* @file otg/otgcore/otg-fw-df.c
* @brief OTG Firmware - Firmware for df
*
* This file defines the OTG State Machine tests.
*
*
* @ingroup OTGFW
*/

/*!
* @page OTGFW
* @section OTGFW_SECTION - otg-fw-df.c
* This contains the input, output and timout definitions for the OTG state machine firmware
*/


#ifdef OTG_APPLICATION
#define NULL 0
#include "otg-fw.h"
#include "otg-fw-df.h"
#else   /* OTG_APPLICATION/ */
#include <otg/otg-compat.h>
#include <otg/usbp-chap9.h>
#include <otg/usbp-func.h>
#include <otg/usbp-bus.h>
#include <otg/otg-trace.h>
//#include <otg/otg-api.h>
#include <otg/otg-fw.h>
#include <otg/otg-fw-df.h>
#endif  /* OTG_APPLICATION */

char            otg_fw_name_df[] = "otg_df";


struct otg_test otg_tests_df[] = {
        /*
         * Copyright (c) 2005-2007 Belcarra Technologies 2005 Corp
         *
         */
        /*!
         * This is the default Firmware. It is included in the
         * compiled modules and supports the auto Traditional USB
         * mode. No user inputs are implemented.
         */
        {                                        /*   */
         0,                                      /* .test */
         invalid_state,                          /* .state */
         otg_disabled,                           /* .target */
         enable_otg,                             /* .test1 */
         },
        /*
         * This is not an OTG State. It is used internally to mark the end of the
         * list of states and inputs.
         */
        {                                        /*   */
         1,                                      /* .test */
         terminator_state,                       /* .state */
         invalid_state,                          /* .target */
         0,                                      /* .test1 */
         },
        {2, invalid_state,},

};

#define OTG_TESTS_DF 2

int             otg_test_max_df = 2;

 /* eof */

/* Generated by otg-info-c.awk
 *
 * Do not Edit, see otg-state.awk
 */

/* %Z %K */

struct otg_state otg_states_df[OTG_STATES_DF + 1] = {
        {                                        /* 0 */
         invalid_state,                          /* .state */
         m_otg_init,                             /* .meta */
         "invalid_state",                        /* .name */
         0,                                      /* .tmout */
         0,                                      /* .reset */
         },
        {                                        /* 1 */
         otg_disabled,                           /* .state */
         m_otg_init,                             /* .meta */
         "otg_disabled",                         /* .name */
         0,                                      /* .tmout */
         0,                                      /* .reset */
         },
        {                                        /* 2 */
         terminator_state,                       /* .state */
         m_otg_init,                             /* .meta */
         "terminator_state",                     /* .name */
         0,                                      /* .tmout */
         0,                                      /* .reset */
         /* .outputs */
         0,
         },

        {0, 0, "", 0, 0,},

};

struct otg_firmware otg_firmware_df = {
        OTG_STATES_DF,                           /* number of states */
        OTG_TESTS_DF,                            /* number of tests */
        "otg-df",                                /* name of firmware */
        otg_states_df,                           /* struct otg_state * */
        otg_tests_df,                            /* struct otg_test * */
};

/* eof */
