# Backlight & LCD drivers

obj-$(CONFIG_LCD_CLASS_DEVICE)     += lcd.o
obj-$(CONFIG_LCD_LTV350QV)	+= ltv350qv.o

obj-$(CONFIG_BACKLIGHT_CLASS_DEVICE) += backlight.o
obj-$(CONFIG_BACKLIGHT_CORGI)	+= corgi_bl.o
obj-$(CONFIG_BACKLIGHT_HP680)	+= hp680_bl.o
obj-$(CONFIG_BACKLIGHT_LOCOMO)	+= locomolcd.o
obj-$(CONFIG_BACKLIGHT_PROGEAR) += progear_bl.o
obj-$(CONFIG_BACKLIGHT_CARILLO_RANCH) += cr_bllcd.o

obj-$(CONFIG_BACKLIGHT_MXC_LCDC) += mxc_lcdc_bl.o
obj-$(CONFIG_BACKLIGHT_MXC_IPU)	+= mxc_ipu_bl.o
obj-$(CONFIG_BACKLIGHT_MXC_PMIC) += mxc_pmic_bl.o
obj-$(CONFIG_BACKLIGHT_WM8350) += wm8350_bl.o
