/*
 * Copyright 2005-2007 Freescale Semiconductor, Inc. All Rights Reserved.
 */

/*
 * The code contained herein is licensed under the GNU General Public
 * License. You may obtain a copy of the GNU General Public License
 * Version 2 or later at the following locations:
 *
 * http://www.opensource.org/licenses/gpl-license.html
 * http://www.gnu.org/copyleft/gpl.html
 */

/* Generated by otg-states-h.awk
 *
 * Do not Edit thie file
 */

/* %Z %K */

/*!
* @file otg/otg/otg-fw-df.h
* @brief OTG Firmware - Firmware for df
*
* This file defines the OTG State Machine tests.
*
* @ingroup OTGFW
*/


/*!
* @page OTGFW
* @section OTGFW_SECTION - otg-fw-df.h
* This contains the input, output and timout definitions for the OTG state machine firmware
*/
extern char     otg_fw_name_df[];
extern int      otg_test_max_df;
extern struct otg_test otg_tests_df[];

 /*
  * Copyright (c) 2005-2007 Belcarra Technologies 2005 Corp
  *
  */
 /*!
  * This is the default Firmware. It is included in the
  * compiled modules and supports the auto Traditional USB
  * mode. No user inputs are implemented.
  */

#define invalid_state                   0        /*  State machine has been initialized. */

#define otg_disabled                    1        /*  State machine has been initialized. */

#define terminator_state                2        /*  terminator */
 /*
  * This is not an OTG State. It is used internally to mark the end of the
  * list of states and inputs.
  */

#define OTG_STATES_DF      3

/* @} */

extern struct otg_state otg_states_df[OTG_STATES_DF + 1];

extern char    *otg_get_state_name_df(int);

extern struct otg_firmware otg_firmware_df;
