#!/bin/sh
#
# System initialisation


# Mount read/write filesystem
/bin/mount -t yaffs -o noatime /dev/mtdblock/2 /mnt/yaffs

# Factory reset
if /usr/bin/test -f /mnt/yaffs/.factoryreset; then
	/bin/echo "FACTORY RESET"

	/bin/umount /mnt/yaffs
	/usr/sbin/flash_eraseall -q /dev/mtd/2
	/bin/mount -t yaffs -o noatime /dev/mtdblock/2 /mnt/yaffs
fi

# Mount overlay filesystem
/sbin/insmod mini_fo.ko
/bin/mount -t mini_fo -o base=/,sto=/mnt/yaffs / /mnt/overlay

# Mount devfs filesystem in overlay
/bin/mount -o move /dev /mnt/overlay/dev

# Run init process
# XXXX remove .noinit option from production?
if /usr/bin/test -f /mnt/yaffs/.noinit; then
	exec /bin/sh
else
	exec /usr/sbin/chroot /mnt/overlay /sbin/init
fi

/bin/echo "Failed to run init"
exec /bin/sh

exit 1

